language: python
python:
  - "2.7"
install:
  - pip install flask
  - pip install flask_socketio
  - pip install numpy
  - pip install matplotlib
  - pip install plotly
  - pip install scipy
  - pip install scikit-image
  - pip install functools32
  - pip install pillow
  - pip install libtiff
  - pip install opencv-python
script:
  - python code/functions/pipeline.py
